name: Build and Deploy

on:
  push: {branches: ["master", "main"]}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Replace API key and build
        run: |
          sed -i 's/process.env.API_KEY/"'$API_KEY'"/' app.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .  
          github_token: ${{ secrets.GITHUB_TOKEN }}
