name: Weather Job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: '16.x'
        
        

    - name: Weather App
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: node app.js
