name: Weather Job

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2.4.2
      with:
        node-version: '14.x'

    - name: Weather App
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: node app.js
