name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2.5.2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: echo $WEATHER_API_KEY > .env

    - name: Run tests
      run: npm test
