name: Build and Deploy

on:
  push: {branches: ["master", "main"]}

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm app.js build
      env:
        API_KEY: ${{ secrets._APIKey }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
