name: Build and Deploy

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Replace API_KEY in app.js
        run: |
          sed -i 's/process.env.API_KEY/"'$API_KEY'"/' app.js
        env:
          API_KEY: ${{ secrets._APIKey }}


      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy app.js and index.html
        run: |
          cp app.js dist/
          cp index.html dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
